server:
  port: 8210
#  port: 0

spring:
  config:
    import:
      - classpath:eureka.client.config.yml
  application:
    name: question-socket-service
  main:
    allow-bean-definition-overriding: true

nextfeed:
  socket:
    endpoint:
      prefix: "/socket/question-socket"