server:
#  port: 8020
  port: 0

spring:
  application:
    name: user-service

  main:
    allow-bean-definition-overriding: true
  config:
    import: classpath:config.yml


  kafka:

    consumer:
      group-id: user-service
    admin:
      client-id: user-service-${server.port}

management:
  endpoints:
    jmx:
      exposure:
        include: health,info,env,beans
    web:
      exposure:
        include: health,info,env,beans

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8000/eureka}
  instance:
    hostname: localhost
    preferIpAddress: true
