server:
  port: 8030

spring:
  config:
    import:
      - classpath:security.config.yml
      - classpath:eureka.client.config.yml
  application:
    name: session-service
  main:
    allow-bean-definition-overriding: true
