spring:
  config:
    import:
      - classpath:nextfeed.config.yml
      - classpath:security.config.yml
  application:
    name: session-service
  main:
    allow-bean-definition-overriding: true

server:
  port: ${nextfeed.service.session-service.port}
