server:
  port: 8001

spring:
  main:
    allow-bean-definition-overriding: true

  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: obsolet-service
          uri: lb://obsolet-service
          predicates:
            - Path=/api/obsolet-service/**
        - id: session-service
          uri: lb://session-service
          predicates:
            - Path=/api/session-service/**
        - id: survey-service
          uri: lb://survey-service
          predicates:
            - Path=/api/survey-service/**

        - id: session-socket
          uri: lb://session-socket
          predicates:
            - Path=/socket/session-socket/**
        - id: survey-socket
          uri: lb://survey-socket
          predicates:
            - Path=/socket/survey-socket/**
        - id: question-socket
          uri: lb://question-socket
          predicates:
            - Path=/socket/question-socket/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8000/eureka}
  instance:
    instanceId: ${spring.application.name}:${random.value}
    hostname: localhost
    preferIpAddress: true





