server:
  port: 8001

spring:
  main:
    allow-bean-definition-overriding: true

  application:
    name: gateway-service
  cloud:
    gateway:
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: false
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowCredentials: true
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"



      routes:
        - id: mood-service
          uri: http://mood-service.nextfeed:8010
          predicates:
            - Path=/api/mood-service/**,/socket/mood-socket/**

        - id: question-service
          uri: http://question-service.nextfeed:8020
          predicates:
            - Path=/api/question-service/**,/socket/question-socket/**

        - id: session-service
          uri: http://session-service.nextfeed:8030
          predicates:
            - Path=/api/session-service/**,/socket/session-socket/**

        - id: survey-service
          uri: http://survey-service.nextfeed:8040
          predicates:
            - Path=/api/survey-service/**,/socket/survey-socket/**

        - id: authorization-service
          uri: http://authorization-service.nextfeed:8050
          predicates:
            - Path=/api/authorization-service/**


management:
  endpoints:
    gateway:
      enabled: true
    jmx:
      exposure:
        include: health,info,env,beans
    web:
      exposure:
        include: health,info,env,beans,prometheus,gateway,metrics
    metrics:
      enabled:
        all: true




