server:
  port: 8001

spring:
  main:
    allow-bean-definition-overriding: true

  application:
    name: gateway-service
  cloud:
    gateway:
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: false
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowCredentials: true
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"



      routes:
        - id: authorization-service
          uri: http://authorization-external-service.nextfeed:8010
          predicates:
            - Path=/api/authorization-service/**
        - id: question-service
          uri: http://question-external-service.nextfeed:8020
          predicates:
            - Path=/api/question-service/**
        - id: session-service
          uri: http://session-external-service.nextfeed:8030
          predicates:
            - Path=/api/session-service/**
        - id: survey-service
          uri: http://survey-external-service.nextfeed:8040
          predicates:
            - Path=/api/survey-service/**


        - id: mood-socket-service
          uri: http://mood-socket-service.nextfeed:8210
          predicates:
            - Path=/socket/mood-socket/**
        - id: session-socket-service
          uri: http://session-socket-service.nextfeed:8230
          predicates:
            - Path=/socket/session-socket/**
        - id: survey-socket-service
          uri: http://survey-socket-service.nextfeed:8240
          predicates:
            - Path=/socket/survey-socket/**
        - id: question-socket-service
          uri: http://question-socket-service.nextfeed:8220
          predicates:
            - Path=/socket/question-socket/**

        - id: test-service
          uri: http://test-service.nextfeed:80
          predicates:
            - Path=/test/**




management:
  endpoints:
    gateway:
      enabled: true
    jmx:
      exposure:
        include: health,info,env,beans
    web:
      exposure:
        include: health,info,env,beans,prometheus,gateway,metrics
    metrics:
      enabled:
        all: true




