server:
  port: 8001

spring:
  main:
    allow-bean-definition-overriding: true

  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowCredentials: true
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"



      routes:
        - id: obsolet-service
          uri: lb://obsolet-service
          predicates:
            - Path=/api/obsolet-service/**
        - id: session-service
          uri: lb://session-service
          predicates:
            - Path=/api/session-service/**
        - id: survey-service
          uri: lb://survey-service
          predicates:
            - Path=/api/survey-service/**

        - id: session-socket-service
          uri: lb://session-socket-service
          predicates:
            - Path=/socket/session-socket/**
        - id: survey-socket-service
          uri: lb://survey-socket-service
          predicates:
            - Path=/socket/survey-socket/**
        - id: question-socket-service
          uri: lb://question-socket-service
          predicates:
            - Path=/socket/question-socket/**

eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8000/eureka}
  instance:
    instanceId: ${spring.application.name}:${random.value}
    hostname: localhost
    preferIpAddress: true





