spring:
  config:
    import:
      - classpath:nextfeed.config.yml
      - classpath:db.config.yml
  application:
    name: session-manager-service
  main:
    allow-bean-definition-overriding: true

server:
  port: ${nextfeed.service.session-manager-service.port}


