server:
  port: 0

spring:
  config:
    import: classpath:config.yml

  kafka:
    consumer:
      group-id: session-manager-service
    admin:
      client-id: session-manager-service-${server.port}

