server:
  port: 8110

spring:
  config:
    import:
#      - classpath:db.config.yml
      - eureka.client.config.yml
  application:
    name: session-manager-service
  main:
    allow-bean-definition-overriding: true


  datasource:
    url: jdbc:postgresql://localhost:5432/nextfeed
    username: root
    password: pw
    driverClassName: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
