#spring:
#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    consumer:
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      properties:
#        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#        spring.json.trusted.packages: com.nextfeed.service.manager.session.entities
#      enable-auto-commit: false
#      auto-offset-reset: earliest
#

#spring.kafka.consumer.properties.spring.json.trusted.packages=com.nextfeed.service.manager.session.entities
##User defined Properties:
nextfeed:
  kafka:
    relays:
      student-a:
        beanName: rtkResultA
        requestTopic: student-a
        replyTopic: result-a
        groupId: student-result-group-b
      student-b:
        beanName: rtkResultB
        requestTopic: student-b
        replyTopic: result-b
        groupId: student-result-group-b