nextfeed:
  config:
    eureka:
      hostname: localhost
      port: 8000

management:
  endpoints:
    jmx:
      exposure:
        include: health,info,env,beans
    web:
      exposure:
        include: health,info,env,beans,refresh
#  info:
#    env:
#      enabled: true

eureka:
  client:
    registry-fetch-interval-seconds: 10
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://${nextfeed.config.eureka.hostname}:${nextfeed.config.eureka.port}/eureka}
  instance:
    instanceId: ${spring.application.name}:${random.value}
    hostname: localhost
    preferIpAddress: true

#info:
#  app:
#    name: my-service
#    version: 1.0.0
#    description: service description
#  author: lecturefeed