management:
  endpoints:
    jmx:
      exposure:
        include: health,info,env,beans
    web:
      exposure:
        include: health,info,env,beans,refresh
#  info:
#    env:
#      enabled: true

eureka:
  client:
    registry-fetch-interval-seconds: 10
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8000/eureka}
  instance:
    instanceId: ${spring.application.name}:${random.value}
    hostname: localhost
    preferIpAddress: true

#info:
#  app:
#    name: order-service
#    version: 1.0.0
#    description: you can insert any kind of data in the property file like this
#  author: mafei