nextfeed:
  debug: true
  kubernetes:
    namespace: "nextfeed"
    podLabelKey: "io.kompose.service"
  metrics:
    enabled: false
  service:
    session-service:
      domain: "session-service.${nextfeed.kubernetes.namespace}"
      port: 8030
      grpc-port: 8035

grpc:
  client:
    session-service:
      address: "static://${nextfeed.service.session-service.domain}:${nextfeed.service.session-service.grpc-port}"
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

management:
  endpoints:
    jmx:
      exposure:
        include: health,info,env,beans
    web:
      exposure:
        include: health,info,env,beans,prometheus
    metrics:
      enabled: true

