spring:
  config:
    import:
      - classpath:nextfeed.config.yml
  application:
    name: survey-socket-service
  main:
    allow-bean-definition-overriding: true

server:
  port: ${nextfeed.service.survey-socket-service.port}

nextfeed:
  socket:
    endpoint:
      prefix: "/socket/survey-socket"

