spring:
  config:
    import:
      - classpath:nextfeed.config.yml
  application:
    name: mood-socket-service
  main:
    allow-bean-definition-overriding: true

server:
  port: ${nextfeed.service.mood-socket-service.port}

nextfeed:
  socket:
    endpoint:
      prefix: "/socket/mood-socket"

