spring:
  config:
    import:
      - classpath:security.config.yml
      - classpath:nextfeed.config.yml
  application:
    name: mood-socket-service
  main:
    allow-bean-definition-overriding: true

server:
  port: ${nextfeed.service.mood-socket-service.port}

nextfeed:
  socket:
    endpoint:
      prefix: "/socket/mood-socket"

grpc:
  server:
    port: ${nextfeed.service.mood-socket-service.grpc-port}

