server:
  port: 8110

spring:
  config:
    import:
      - classpath:db.config.yml
      - classpath:eureka.client.config.yml
  application:
    name: mood-manager-service
  main:
    allow-bean-definition-overriding: true
