nextfeed:
  datasource:
    host: localhost
    port: 5411
    db: nextfeed
    username: root
    pw: pw
    show-sql: true

spring:
  config:
    import:
      - classpath:nextfeed.config.yml
      - classpath:db.config.yml
  application:
    name: mood-repository-service
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:postgresql://${nextfeed.datasource.host}:${nextfeed.datasource.port}/${nextfeed.datasource.db}
    username: ${nextfeed.datasource.username}
    password: ${nextfeed.datasource.pw}
  jpa:
    show-sql: ${nextfeed.datasource.show-sql}


server:
  port: ${nextfeed.service.mood-repository-service.port}
