server:
  port: 8120

spring:
  config:
    import:
      - classpath:db.config.yml
      - classpath:eureka.client.config.yml
  application:
    name: participant-manager-service
  main:
    allow-bean-definition-overriding: true
