server:
  port: 8120

spring:
  config:
    import:
      - classpath:db.config.yml
      - classpath:eureka.client.config.yml
  application:
    name: participant-manager-service
  main:
    allow-bean-definition-overriding: true

#  datasource:
#    url: jdbc:h2:file:~/NEXTFEED_DB;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#  jpa:
#      database-platform: org.hibernate.dialect.H2Dialect
#      properties:
#        hibernate:
#          globally_quoted_identifiers: true
#      show-sql: true
#      hibernate:
#        ddl-auto: update
#    h2:
#      console:
#        enabled: true
#        #http://localhost:8050/h2-console/



