nextfeed:
  datasource:
    host: localhost
    port: 5411
    db: nextfeed
    username: root
    pw: pw
    show-sql: true

  socket:
    endpoint:
      prefix: "/socket/mood-socket"

spring:
  config:
    import:
      - classpath:nextfeed.config.yml
      - classpath:security.config.yml
      - classpath:db.config.yml
  application:
    name: mood-service
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:postgresql://${nextfeed.datasource.host}:${nextfeed.datasource.port}/${nextfeed.datasource.db}
    username: ${nextfeed.datasource.username}
    password: ${nextfeed.datasource.pw}
  jpa:
    show-sql: ${nextfeed.datasource.show-sql}

server:
  port: ${nextfeed.service.mood-service.port}

grpc:
  server:
    port: ${nextfeed.service.mood-service.grpc-port}
